apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: hacking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: carlitos23m/juice-shop:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000